name: Actualizar Datos Fantasy Diariamente

on:
  schedule:
    # Se ejecuta todos los días a las 07:00 AM (Hora UTC)
    - cron: '0 7 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente cuando quieras desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar Robot
        run: python bot.py

      - name: Guardar cambios en el repositorio
        run: |
          git config --global user.name "Bot Fantasy"
          git config --global user.email "bot@fantasy.com"
          git add datos.json
          git commit -m "Auto-actualización de datos Fantasy" || exit 0
          git push
