name: Actualizar Datos Fantasy Diariamente

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar librerías
        run: pip install requests beautifulsoup4

      - name: Ejecutar Robot
        run: python bot.py

      - name: Guardar cambios en el repositorio
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Auto-actualización diaria de datos fantasy" || echo "Sin cambios"
          git push