name: Actualizar Datos Fantasy Diariamente

on:
  workflow_dispatch: # Permite ejecutarlo manualmente cuando quieras
  schedule:
    - cron: '0 5 * * *' # Se ejecuta automáticamente TODAS LAS NOCHES a las 5:00 AM UTC (6:00/7:00 AM España)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar librerías
        run: pip install requests beautifulsoup4

      - name: Ejecutar Robot
        run: python bot.py

      - name: Guardar cambios en el repositorio
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add datos.json
          git commit -m "Auto-actualización nocturna de la base de datos Fantasy" || echo "Sin cambios"
          git push